#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  cd /home/spoke/app
  # shellcheck source=/dev/null
  source ~/.nvm/nvm.sh
  nvm use
  if [[ -f ./build/server/server/index.js ]]; then
    exec node ./build/server/server
  fi
  exec npm start
}

main "${@}"
