name: terraform
on: [push, pull_request]
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: fmt
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: fmt
    - name: init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: init
    - name: validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.21
        tf_actions_subcommand: validate
